version: "3"

services:

  frontend:
    image: traefik-frontend
    build: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/var/www/html
      - /var/www/html/node_modules
    labels:
      - "traefik.http.routers.frontend.rule=Host(`app.localhost`)"
      - "traefik.docker.network=default"
    depends_on:
      - traefik

  backend:
    image: traefik-backend
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    labels:
      - "traefik.http.routers.backend.rule=(Host(`app.localhost`) && PathPrefix(`/api`))"
      - "traefik.docker.network=default"
    depends_on:
      - traefik

  traefik:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
